---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    admin.password: AgByXzLtxRcjq8QRGhUuxpzOkWQymi8eEx7frqzpHn713SFLSZpy4a2i7v2zFma5Upf6chmyAjX8QTRTs4DESVcnmWxXKjDcucLsgAvmerO7aB9Al+4bW0eSUaxg30SPILdH8TjasRnAJlgOHr76ly84e5Gm3OWFScEREXe7xgE+dWaRXRj/3TZL3YRiK4Heg0CK11noB4XfhoaKhBQ+yS4I71Wft7JdB6lLKUi8cMlAJgMkU1EqoVv7INjGiSDoTC5t636JvGNJ36DomKKo7CGMTYSWC6wgDUCIXDVvsCdEtc26TCbg8JZcNDJTM75b3dadbnCXS/vobhNedIk+MCXGfYPjxIlK+YobxH8ulJxEmQ4oaAZJRvOKg9tVGIM1x/U6iPJDf/UiueyRRGeWCMjln8V4HGU3NETIbYfhqo4tBMLXSVTHsUf5Pr2Ze5ZwZwPzcVMw2W9JAJ6UETiMRxQkYHQjAtCSiiB5ZuXB7xdpC9rw34AYeIwbDLL/DZ21kMGAsVrjDXbDsimgK5+AmQgsb4EKLPd/We1mUucVRB/2JC35B48v2m6BH2eeGrFwRHi+5xVbBvl9UkZ7l5j5HpeVkuyLl24sUg7XYh1/UIfjVR1dyeoEWqb9t/bowcojb9T1nRyhi+q1O9K/p268vMVfImMZAIdaXzYMpEXnI9awz00gIjiCsElm0x2zr+CWCAFvZjauQLFn2yPc316QvmAkMPxEES4gu4mfYH9iEvSjjNIApkTZiR91KX5NB9QcpbOQM4Lg0ITa7QCaswo=
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-secret
        app.kubernetes.io/part-of: argocd
      name: argocd-secret
      namespace: argocd
    type: Opaque
