apiVersion: v1
kind: Namespace
metadata:
  name: brachi
---
apiVersion: v1
kind: Service
metadata:
  name: brachi
  namespace: brachi
spec:
  ports:
    - name: web
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: brachi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: brachi
  namespace: brachi
  labels:
    app: brachi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brachi
  template:
    metadata:
      labels:
        app: brachi
    spec:
      containers:
        - name: brachi
          image: ghcr.io/incognito124/brachi:1767733870
          ports:
            - name: web
              containerPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: brachi
  namespace: brachi
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: "letsencrypt"
    traefik.ingress.kubernetes.io/router.middlewares: "argocd-redirect-https@kubernetescrd"
spec:
  ingressClassName: traefik
  rules:
    - host: brachi.msmetko.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: brachi
                port:
                  number: 80
